[package]
name = "rquickjs-mre"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rquickjs = {version = "0.9.0", features = ["futures"]}
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = {version = "1", features = ["full"]}
